# Site wide configuration

title: Site Title
locale: en_US
description: We are what we repeatedly do. Excellence, therefore, is not an act, but a habit.
logo: site-logo.png
search: true
url: http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: GuoJunjun
  avatar: bio-photo.jpg
  website: JunjunGuo.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: github.com/junjunguo
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: linkedin.com/in/guojunjun
  instagram: #username
  flickr: https://www.flickr.com/photos/guojunjun/
  tumblr: #username
  google:
    plus: https://plus.google.com/+JunjunGuo
    analytics: UA-49981756-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:

# Disqus Comments
site:
   owner:
     disqus-shortname: guojunjunsblog
# If you would like comments to appear on every post or page that uses the post.html
comments: true